title: Easy Jekyll
description: >-
  Wow it's never been easier to use jekyll!

# url system:
baseurl: "" # if you gona run he in localhost remember to define null or use "$ jekyll server --baseurl=''"
url: ""

# source and structure settings
destination: _app/website

# others:
github_username: gabrielramires

# Theme:
theme: minima # Just a Remember: if you change this its mayable of the default files in the _includes/content/custom not works.
plugins:
  - jekyll-feed
  - jekyll-seo-tag
