# Warns:
# Any errors appear in the site console!
# If the file not work and no have any error in the console verify if the file is enabled else verify the sub_path.

files_confirmation:
  - name: "page_empty"
    desc: "If the Page stay Empty the user goto a error page 204"
    enabled: true

  - name: "water_mark"
    desc: "Cool Water Mark from the template but if you don't like remove he changing the value enabled to false in the module_config.yml"
    enabled: true

config:
  enabled: true
  normal_path: content/custom
