files_confirmation:
  - name: "page_empty"
    desc: "If the Page stay Empty the user goto a error page 204"
    enabled: true
    sub_path: ""

  - name: "water_mark"
    desc: "Cool Water Mark from the template but if you don't like remove he changing the value enabled to false in the module_config.yml"
    enabled: true
    sub_path: "console/log" # Attetions its work like this: if the file its into a another folder in the custom folder you need add the patch exemple: my file into a "script" you need put: "script" or another exemple: my file into a "script/lua"  you need put: "script/lua" difene null if the file its into a custom
