# Warns:
# Any errors appear in the site console!
# If the file not work and no have any error in the console verify if the normal_path its correct.

files_args_configs:
  - file_name: "figures"
    args1: type

config:
  enabled: true
  normal_path: content/modules
